name: VeepaPOC
options:
  bundleIdPrefix: com.veepapoc
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

schemes:
  VeepaPOC:
    build:
      targets:
        VeepaPOC: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - VeepaPOCTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    ENABLE_USER_SCRIPT_SANDBOXING: NO

targets:
  VeepaPOC:
    type: application
    platform: iOS
    sources:
      - path: VeepaPOC
        excludes:
          - "**/.DS_Store"
      - path: Flutter/GeneratedPluginRegistrant.h
      - path: Flutter/GeneratedPluginRegistrant.m
      # Veepa SDK plugin files
      - path: SDK/VsdkPlugin.h
      - path: SDK/VsdkPlugin.m
      - path: SDK/AppP2PApiPlugin.h
      - path: SDK/AppPlayerPlugin.h
    resources:
      - path: Resources
        excludes:
          - "**/.DS_Store"
    dependencies:
      # Flutter frameworks - use Release for standalone operation
      - framework: Flutter/Release/Flutter.xcframework
        embed: true
      - framework: Flutter/Release/App.xcframework
        embed: true
      - framework: Flutter/Release/connectivity_plus.xcframework
        embed: true
      - framework: Flutter/Release/Reachability.xcframework
        embed: true
      - framework: Flutter/Release/path_provider_foundation.xcframework
        embed: true
      - framework: Flutter/Release/permission_handler_apple.xcframework
        embed: true
      - framework: Flutter/Release/shared_preferences_foundation.xcframework
        embed: true
      # Veepa SDK static library (device only - no simulator support)
      - framework: SDK/libVSTC.a
        embed: false
      # System libraries required by Veepa SDK
      - sdk: libz.tbd
      - sdk: libc++.tbd
      - sdk: libiconv.tbd
      - sdk: libbz2.tbd
      # System frameworks required by Veepa SDK
      - sdk: AVFoundation.framework
      - sdk: VideoToolbox.framework
      - sdk: AudioToolbox.framework
      - sdk: CoreMedia.framework
      - sdk: CoreVideo.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.veepapoc.host
        INFOPLIST_FILE: VeepaPOC/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES: YES
        SWIFT_OBJC_BRIDGING_HEADER: VeepaPOC/App/VeepaPOC-Bridging-Header.h
        # Add SDK folder to header search paths
        HEADER_SEARCH_PATHS: "$(inherited) $(SRCROOT)/SDK"
        # Add SDK folder to library search paths
        LIBRARY_SEARCH_PATHS: "$(inherited) $(SRCROOT)/SDK"

  VeepaPOCTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/VeepaPOCTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: VeepaPOC
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
