name: VeepaPOC
options:
  bundleIdPrefix: com.veepapoc
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    ENABLE_USER_SCRIPT_SANDBOXING: NO

targets:
  VeepaPOC:
    type: application
    platform: iOS
    sources:
      - path: VeepaPOC
        excludes:
          - "**/.DS_Store"
      - path: Flutter/GeneratedPluginRegistrant.h
      - path: Flutter/GeneratedPluginRegistrant.m
    resources:
      - path: Resources
        excludes:
          - "**/.DS_Store"
    dependencies:
      - framework: Flutter/Debug/Flutter.xcframework
        embed: true
      - framework: Flutter/Debug/App.xcframework
        embed: true
      - framework: Flutter/Debug/connectivity_plus.xcframework
        embed: true
      - framework: Flutter/Debug/Reachability.xcframework
        embed: true
      - framework: Flutter/Debug/path_provider_foundation.xcframework
        embed: true
      - framework: Flutter/Debug/permission_handler_apple.xcframework
        embed: true
      - framework: Flutter/Debug/shared_preferences_foundation.xcframework
        embed: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.veepapoc.host
        INFOPLIST_FILE: VeepaPOC/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES: YES
        SWIFT_OBJC_BRIDGING_HEADER: VeepaPOC/App/VeepaPOC-Bridging-Header.h

  VeepaPOCTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/VeepaPOCTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: VeepaPOC
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
